### ISSUE TITLE
Velociraptor Creds Wrong

### ISSUE THREAD

**Issue by rquarry** [iknowjason/BlueCloud#2]
azure/modules/velocihelk-vm/playbook-velociraptor.yml line 28 sets velociraptor credentials to "helk helk" but docks say "vadmin:vadmin"

**Comment by iknowjason** [comment]
Thank you @rquarry, nice catch!  Updated.

**Comment by iknowjason** [comment]
The actual credentials are correct.  The documentation needs to change.  The Azure directory has the credentials of helk:helk and the PurpleCloud project does as well.  Making this easier for uniformity.  The documentation had an error.
