### ISSUE TITLE
This object does not have an attribute named "this_key_pair_key_name"

### ISSUE THREAD

**Issue by Spartan-Cybersecurity** [iknowjason/BlueCloud#4]
terraform apply -var-file=terraform.tfvars
var.key_name
  Enter a value: blueteam

var.private_key
  Enter a value: blueteam

╷
│ Error: Unsupported attribute
│
│   on main.tf line 72, in module "velocihelk":
│   72:   key_name                  = module.key_pair.this_key_pair_key_name
│     ├────────────────
│     │ module.key_pair is a object, known only after apply
│
│ This object does not have an attribute named "this_key_pair_key_name".
╵
╷
│ Error: Unsupported attribute
│
│   on main.tf line 82, in module "ws2019":
│   82:   key_name                   = module.key_pair.this_key_pair_key_name
│     ├────────────────
│     │ module.key_pair is a object, known only after apply
│
│ This object does not have an attribute named "this_key_pair_key_name".

**Comment by iknowjason** [comment]
@Spartan-Cybersecurity Checking this out and will get back with you shortly.

**Comment by iknowjason** [comment]
@Spartan-Cybersecurity Issue has been resolved with key pair object reference.  Please do a git pull for latest.  If you don't mind letting me know that this resolves all of your issues, appreciate the feedback.

**Comment by Spartan-Cybersecurity** [comment]
Thank you very much!
Everything worked perfectly!
I found it an excellent contribution to the community!
